#!/bin/sh

# default value
cover="cover.jpg"

if [ $# -ge 1 ]; then
    cover=$"1"
fi

if  [ ! -f $cover ]; then
echo "$cover" is not a file"
 exit -1
fi

echo "Importing $cover"

metaflac --import-picture-from="3|image/jpeg|||$cover" *.flac







